source 'https://github.com/CocoaPods/Specs.git'

target 'startup' do

    ######################################
    # 主框架
    #  * 外部引用
    #    - pod 'oc-foundation', :git => 'https://github.com/fallending/oc-suite.git'
    ######################################
    
    pod '_Foundation', :path => '../' # pod '_Foundation', :git => 'https://github.com/fallending/oc-suite.git'
    pod '_Building', :path => '../'
    
    pod '_Tool/NetworkLit', :path => '../'
    pod '_Tool/Network/Reachability', :path => '../'
    pod '_Tool/Cache', :path => '../'
    pod '_Tool/HttpMock', :path => '../'
    pod '_Tool/Database', :path => '../'
#    pod '_Tool/NoSQL', :path => '../'
    pod '_Tool/Utility', :path => '../'
    pod '_Tool/Date', :path => '../'
    
    pod '_Modular', :path => '../'
    
    pod '_Components/ActionSheetView', :path => '../'
    pod '_Components/AlertView', :path => '../'
    pod '_Components/BadgeView', :path => '../'
    pod '_Components/BlankHolderView', :path => '../'
    pod '_Components/CycleScrollView', :path => '../'
    pod '_Components/DatePickerView', :path => '../'
    pod '_Components/DropDownMenu', :path => '../'
    pod '_Components/FiniteScrollView', :path => '../'
    pod '_Components/FlatActionSheetView', :path => '../'
#    pod '_Components/ImageBrowserView', :path => '../'
    pod '_Components/ImagePicker', :path => '../'
    pod '_Components/IndicatorView', :path => '../'
    pod '_Components/InfiniteScrollView', :path => '../'
    pod '_Components/KeyboardControl', :path => '../'
    pod '_Components/LaunchAdView', :path => '../'
    pod '_Components/LoadableImageView', :path => '../'
    
    pod '_Components/LocalImageBrowser', :path => '../'
    pod '_Components/LocalImageEditableBrowserView', :path => '../'
    pod '_Components/PopupView', :path => '../'
    pod '_Components/PopViewController', :path => '../'
    pod '_Components/ProgressHUD', :path => '../'
#    pod '_Components/QRCodeReaderView', :path => '../'

    pod '_Components/PopViewController', :path => '../'
    pod '_Components/RateView', :path => '../'
    pod '_Components/RefreshView', :path => '../'
    pod '_Components/SegmentControl', :path => '../'
    pod '_Components/SegmentView', :path => '../'
    pod '_Components/TagsView', :path => '../'
    pod '_Components/UserGuideView', :path => '../'
    pod '_Components/WaterFallView', :path => '../'
    
    pod '_Modules/Components/Application', :path => '../'
    
    pod '_Modules/Components/QRCodeReader', :path => '../'
    pod '_Modules/Components/WebBrowser', :path => '../'
    
    pod '_Modules/Services/Assets', :path => '../'
    pod '_Modules/Services/Growth', :path => '../'

    ######################################
    # 其他依赖
    ######################################
    
    pod 'ReactiveObjC'
    
    pod 'Masonry'
    
    pod 'YYModel'
    
    pod 'SDWebImage', '~> 4.0'
    
    pod 'AFNetworking', '~> 3.0'
    
    # pod 'RealReachability' # 非网络连接状态，而是网络到达状态，比如：Wi-Fi 并 能否连接到www.baidu.com
    
    # pod 'TransitionKit', '~> 2.0.0' # 状态机
    
    # pod 'Objective-Chain'
    
    # pod 'JHChainableAnimations', '~> 3.0.1' # While use 'ChainableAnimations' in Swift

    # pod 'RegexKitLite' # 正则表达式
    
    ######################################
    # UI 组件
    ######################################
    
    # 抽屉
    #pod "JVFloatingDrawer"
    
    # 类似网易新闻、今日头条、虎扑看球等app做的一个顶部菜单栏，每栏中有独立的控制器，可自己定制。
    # pod 'NinaPagerView'
    # pod 'MXSegmentedPager'

end
