source 'https://github.com/CocoaPods/Specs.git'

target 'startup' do

    ######################################
    # 主框架
    #  * 外部引用
    #    - pod 'oc-foundation', :git => 'https://github.com/fallending/oc-suite.git'
    ######################################
    
    pod '_Foundation', :path => '../' # pod '_Foundation', :git => 'https://github.com/fallending/oc-suite.git'
    pod '_UI', :path => '../'
    
    
    pod '_Tool/NetworkLit', :path => '../'
    pod '_Tool/Network/Reachability', :path => '../'
    pod '_Tool/Cache', :path => '../'
    pod '_Tool/HttpMock', :path => '../'
    
    ######################################
    # 其他依赖
    ######################################
    
    pod 'Masonry'
    
    pod 'YYModel'
    
    #    pod 'RealReachability' # 非网络连接状态，而是网络到达状态，比如：Wi-Fi 并 能否连接到www.baidu.com
    
    # pod 'TransitionKit', '~> 2.0.0' # 状态机

    
    ######################################
    # UI 组件
    ######################################
    
    # 抽屉
    #pod "JVFloatingDrawer"
    
    # 类似网易新闻、今日头条、虎扑看球等app做的一个顶部菜单栏，每栏中有独立的控制器，可自己定制。
    # pod 'NinaPagerView'
    # pod 'MXSegmentedPager'

end
