
#define font_normal_7    [UIFont systemFontOfSize:7]
#define font_normal_8    [UIFont systemFontOfSize:8]
#define font_normal_9    [UIFont systemFontOfSize:9]
#define font_normal_10   [UIFont systemFontOfSize:10]
#define font_normal_11   [UIFont systemFontOfSize:11]
#define font_normal_12   [UIFont systemFontOfSize:12]
#define font_normal_13   [UIFont systemFontOfSize:13]
#define font_normal_14   [UIFont systemFontOfSize:14]
#define font_normal_15   [UIFont systemFontOfSize:15]
#define font_normal_16   [UIFont systemFontOfSize:16]
#define font_normal_17   [UIFont systemFontOfSize:17]
#define font_normal_18   [UIFont systemFontOfSize:18]
#define font_normal_19   [UIFont systemFontOfSize:19]
#define font_normal_20   [UIFont systemFontOfSize:20]
#define font_normal_21   [UIFont systemFontOfSize:21]
#define font_normal_22   [UIFont systemFontOfSize:22]
#define font_normal_23   [UIFont systemFontOfSize:23]
#define font_normal_24   [UIFont systemFontOfSize:24]
#define font_normal_32   [UIFont systemFontOfSize:32]
#define font_normal_33   [UIFont fontWithName:@"Helvetica" size:33.0]

#define font_bold_7    [UIFont boldSystemFontOfSize:7]
#define font_bold_8    [UIFont boldSystemFontOfSize:8]
#define font_bold_9    [UIFont boldSystemFontOfSize:9]
#define font_bold_10   [UIFont boldSystemFontOfSize:10]
#define font_bold_11   [UIFont boldSystemFontOfSize:11]
#define font_bold_12   [UIFont boldSystemFontOfSize:12]
#define font_bold_13   [UIFont boldSystemFontOfSize:13]
#define font_bold_14   [UIFont boldSystemFontOfSize:14]
#define font_bold_15   [UIFont boldSystemFontOfSize:15]
#define font_bold_16   [UIFont boldSystemFontOfSize:16]
#define font_bold_17   [UIFont boldSystemFontOfSize:17]
#define font_bold_18   [UIFont boldSystemFontOfSize:18]
#define font_bold_19   [UIFont boldSystemFontOfSize:19]
#define font_bold_20   [UIFont boldSystemFontOfSize:20]
#define font_bold_21   [UIFont boldSystemFontOfSize:21]
#define font_bold_22   [UIFont boldSystemFontOfSize:22]
#define font_bold_23   [UIFont boldSystemFontOfSize:23]
#define font_bold_24   [UIFont boldSystemFontOfSize:24]
#define font_bold_32   [UIFont boldSystemFontOfSize:32]
#define font_bold_33   [UIFont fontWithName:@"Helvetica-Bold" size:33.0]

